sonar.projectKey=hevy-personal-dashboard-app
sonar.projectName=Hevy Personal-Dashboard-App
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts
sonar.exclusions=src/**/*.spec.ts,src/test/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.coverage.exclusions=src/types/**,src/main.ts,src/test/**
